version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  core:
    build: core
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DATABASE=${DATABASE}
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine

  celery:
    build: core
    command: celery -A project worker -l info
    depends_on:
      - redis

  celery-beat:
    build: core
    command: celery -A project beat -l info
    depends_on:
      - redis